/**
 * @fileoverview NextAuth.js authentication API routes
 *
 * This module exports the NextAuth.js authentication handlers for managing
 * user authentication flows. NextAuth provides a complete authentication solution
 * with support for various providers (OAuth, credentials, email), session management,
 * and security features.
 *
 * The catch-all route [...nextauth] handles all authentication-related requests:
 * - Sign in/out operations
 * - OAuth provider callbacks
 * - Session management
 * - CSRF token generation
 * - Provider configuration endpoints
 *
 * @module app/api/auth/[...nextauth]
 * @see {@link @/auth} for authentication configuration
 */

import { handlers } from "@/auth"

/**
 * NextAuth.js route handlers for authentication operations.
 *
 * These handlers are generated by NextAuth and provide a complete authentication
 * system through various HTTP endpoints:
 *
 * GET endpoints:
 * - /api/auth/signin - Sign in page
 * - /api/auth/signout - Sign out page
 * - /api/auth/session - Current session data
 * - /api/auth/csrf - CSRF token
 * - /api/auth/providers - Available auth providers
 * - /api/auth/callback/:provider - OAuth callback handler
 *
 * POST endpoints:
 * - /api/auth/signin/:provider - Initiate sign in with provider
 * - /api/auth/signout - Sign out current user
 * - /api/auth/callback/:provider - Process OAuth callback
 * - /api/auth/session - Update session
 *
 * All authentication configuration (providers, callbacks, session strategy, etc.)
 * is defined in the auth configuration file (@/auth).
 *
 * @constant {Object} handlers - The GET and POST route handlers
 * @property {Function} GET - Handler for GET authentication requests
 * @property {Function} POST - Handler for POST authentication requests
 *
 * @requires None - Public endpoints (authentication determines access)
 *
 * @example
 * // Sign in flow:
 * // 1. User visits: GET /api/auth/signin
 * // 2. User selects provider and submits: POST /api/auth/signin/google
 * // 3. OAuth redirect to provider
 * // 4. Provider redirects back: GET /api/auth/callback/google?code=...
 * // 5. Session created, user authenticated
 *
 * @example
 * // Session check:
 * // GET /api/auth/session
 * // Response: { user: { id, name, email, role }, expires: "..." }
 */
export const { GET, POST } = handlers