/**
 * @fileoverview UploadThing API routes for file uploads
 *
 * This module configures and exports the UploadThing route handlers for handling
 * file uploads in the application. UploadThing is a file upload service that provides
 * secure, efficient file handling with automatic CDN distribution.
 *
 * The route handlers (GET and POST) are automatically generated by UploadThing's
 * createRouteHandler utility based on the file router configuration defined in
 * @/lib/uploadthing. These routes handle:
 * - GET: Fetching upload metadata and presigned URLs
 * - POST: Processing completed uploads and storing file information
 *
 * @module app/api/uploadthing
 * @see {@link @/lib/uploadthing} for file router configuration
 */

// app/api/uploadthing/route.ts

import { createRouteHandler } from "uploadthing/next";
import { ourFileRouter } from "@/lib/uploadthing";

/**
 * UploadThing route handlers for file upload operations.
 *
 * These handlers are automatically generated by UploadThing and provide:
 * - GET endpoint: Returns upload configuration and presigned URLs for client uploads
 * - POST endpoint: Handles upload completion callbacks and file metadata storage
 *
 * The router configuration (ourFileRouter) defines allowed file types, size limits,
 * authentication requirements, and upload completion handlers.
 *
 * @constant {Object} handlers - The GET and POST route handlers
 * @property {Function} GET - Handler for fetching upload configuration
 * @property {Function} POST - Handler for processing completed uploads
 *
 * @example
 * // Client-side usage (handled by UploadThing client components):
 * // 1. Client requests upload URL: GET /api/uploadthing
 * // 2. Client uploads file directly to UploadThing CDN
 * // 3. UploadThing calls back: POST /api/uploadthing with file metadata
 * // 4. Server processes metadata and returns response to client
 */
export const { GET, POST } = createRouteHandler({
    router: ourFileRouter,
    config: {
        // Optional: Configure callback URL for production
        // callbackUrl: process.env.UPLOADTHING_CALLBACK_URL,
    },
});